version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: marshallSportBot
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marshallSportBot
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    container_name: marshallSportBotApp
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
