spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/marshallSportBot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db.migration

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

bot:
  token: ${BOT_TOKEN}
  name: ${BOT_USER_NAME}