package com.marshall.sportbot.enums;

public enum Command {
    SEND_PUSH_UP_MENU,
    SEND_PULL_UP_MENU,
    SEND_HELP_MENU,
    SEND_START_MENU,
    SEND_PUSH_UP_ADD_MESSAGE,
    SEND_PUSH_UP_STATS_MESSAGE,
    SEND_PUSH_UP_GOAL_MENU,
    SEND_PULL_UP_ADD_MESSAGE,
    SEND_PULL_UP_STATS_MESSAGE,
    SEND_PULL_UP_GOAL_MENU,


    SET_DAY_PUSH_UP_GOAL,
    SET_WEEK_PUSH_UP_GOAL,
    SET_MONTH_PUSH_UP_GOAL,

    SWITCH_PUSH_UP_NOTIFICATION
}
